### ISSUE TITLE
[Database] App stürzt bei fehlerhafter Datenbank bzw. fehlendem Zugriff ab

### ISSUE THREAD

**Issue by markusressel** [Power-Switch/PowerSwitch_Android#15]
Installiert man PowerSwitch mit einem anderen key bleibt die Datenbank zwar erhalten, die App hat scheinbar aber keinen zugriff mehr darauf. Beim Start der App kommt dann eine Exception und die App stürzt ab.

Dieses Verhalten soll verbessert werden

Exception (evtl. doppelt)

```
06-11 19:44:45.553  32681-32681/de.ekeihland.powerswitch W/ContextImpl﹕ Unable to create files subdir /data/data/de.ekeihland.powerswitch/cache
06-11 19:44:45.553  32681-32681/de.ekeihland.powerswitch E/ActivityThread﹕ Unable to setupGraphicsSupport due to missing cache directory
06-11 19:44:45.623  32681-32681/de.ekeihland.powerswitch D/ContextHelper﹕ convertTheme. context->name=de.ekeihland.powerswitch themeResourceId=2131296419
06-11 19:44:45.669  32681-32681/de.ekeihland.powerswitch I/PhoneWindow﹕ [generateLayout] setColorNavigationBar => color=0x ff000001
06-11 19:44:45.674  32681-32681/de.ekeihland.powerswitch D/PhoneWindowEx﹕ [PWEx][generateLayout] setNavigationBarColor2 : colors=0xff000000
06-11 19:44:45.674  32681-32681/de.ekeihland.powerswitch I/PhoneWindow﹕ [setNavigationBarColor2] color=0x ff000000
06-11 19:44:45.810  32681-32706/de.ekeihland.powerswitch D/libc-netbsd﹕ [getaddrinfo]: hostname=xxxxx; servname=(null); cache_mode=(null), netid=0; mark=0
06-11 19:44:45.810  32681-32706/de.ekeihland.powerswitch D/libc-netbsd﹕ [getaddrinfo]: ai_addrlen=0; ai_canonname=xxxxx; ai_flags=4; ai_family=0
06-11 19:44:45.818  32681-32707/de.ekeihland.powerswitch D/OpenGLRenderer﹕ Render dirty regions requested: true
06-11 19:44:45.820  32681-32707/de.ekeihland.powerswitch I/Adreno-EGL﹕ <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LA.BF.1.1.1_RB1.05.00.02.042.013_msm8974_LA.BF.1.1.1_RB1__release_AU ()
    OpenGL ES Shader Compiler Version: E031.25.03.00
    Build Date: 01/21/15 Wed
    Local Branch: mybranch7061829
    Remote Branch: quic/LA.BF.1.1.1_rb1.7
    Local Patches: NONE
    Reconstruct Branch: AU_LINUX_ANDROID_LA.BF.1.1.1_RB1.05.00.02.042.013 +  NOTHING
06-11 19:44:45.821  32681-32707/de.ekeihland.powerswitch I/OpenGLRenderer﹕ Initialized EGL, version 1.4
06-11 19:44:45.840  32681-32707/de.ekeihland.powerswitch D/OpenGLRenderer﹕ Enabling debug mode 0
06-11 19:44:45.849  32681-32681/de.ekeihland.powerswitch D/Atlas﹕ Validating map...
06-11 19:44:45.916  32681-32706/de.ekeihland.powerswitch E/AutoGatewayDiscover﹕ Timelimit reached
06-11 19:44:45.940  32681-32705/de.ekeihland.powerswitch E/SQLiteLog﹕ (14) cannot open file at line 31279 of [9491ba7d73]
06-11 19:44:45.940  32681-32705/de.ekeihland.powerswitch E/SQLiteLog﹕ (14) os_unix.c:31279: (2) open(/data/data/de.ekeihland.powerswitch/databases/PSdatabase.db) -
06-11 19:44:45.948  32681-32681/de.ekeihland.powerswitch D/RoomsFragment﹕ refreshReceivers
06-11 19:44:45.950  32681-32681/de.ekeihland.powerswitch E/SQLiteLog﹕ (14) cannot open file at line 31279 of [9491ba7d73]
06-11 19:44:45.950  32681-32681/de.ekeihland.powerswitch E/SQLiteLog﹕ (14) os_unix.c:31279: (2) open(/data/data/de.ekeihland.powerswitch/databases/PSdatabase.db) -
06-11 19:44:45.990  32681-32705/de.ekeihland.powerswitch E/SQLiteDatabase﹕ Failed to open database '/data/data/de.ekeihland.powerswitch/databases/PSdatabase.db'.
    android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
            at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
            at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:212)
            at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:196)
            at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:464)
            at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:186)
            at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:178)
            at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:916)
            at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:893)
            at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:796)
            at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1254)
            at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:267)
            at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
            at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
            at de.ekeihland.powerswitch.database.DatabaseHandler.openReadable(DatabaseHandler.java:18)
            at de.ekeihland.powerswitch.database.gateways.GatewayHandler.getAll(GatewayHandler.java:82)
            at de.ekeihland.powerswitch.network.NetworkHandler.searchGateways(NetworkHandler.java:89)
            at de.ekeihland.powerswitch.gui.activity.MainActivity$2.doInBackground(MainActivity.java:86)
            at de.ekeihland.powerswitch.gui.activity.MainActivity$2.doInBackground(MainActivity.java:81)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
06-11 19:44:45.990  32681-32705/de.ekeihland.powerswitch E/SQLiteOpenHelper﹕ Couldn't open PSdatabase.db for writing (will try read-only):
    android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
            at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
            at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:212)
            at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:196)
            at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:464)
            at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:186)
            at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:178)
            at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:916)
            at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:893)
            at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:796)
            at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1254)
            at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:267)
            at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
            at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
            at de.ekeihland.powerswitch.database.DatabaseHandler.openReadable(DatabaseHandler.java:18)
            at de.ekeihland.powerswitch.database.gateways.GatewayHandler.getAll(GatewayHandler.java:82)
            at de.ekeihland.powerswitch.network.NetworkHandler.searchGateways(NetworkHandler.java:89)
            at de.ekeihland.powerswitch.gui.activity.MainActivity$2.doInBackground(MainActivity.java:86)
            at de.ekeihland.powerswitch.gui.activity.MainActivity$2.doInBackground(MainActivity.java:81)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
06-11 19:44:45.990  32681-32705/de.ekeihland.powerswitch E/SQLiteLog﹕ (14) cannot open file at line 31279 of [9491ba7d73]
06-11 19:44:45.990  32681-32705/de.ekeihland.powerswitch E/SQLiteLog﹕ (14) os_unix.c:31279: (2) open(/data/data/de.ekeihland.powerswitch/databases/PSdatabase.db) -
06-11 19:44:45.991  32681-32705/de.ekeihland.powerswitch E/SQLiteDatabase﹕ Failed to open database '/data/data/de.ekeihland.powerswitch/databases/PSdatabase.db'.
    android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
            at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
            at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:212)
            at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:196)
            at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:464)
            at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:186)
            at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:178)
            at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:916)
            at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:893)
            at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:796)
            at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:234)
            at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
            at de.ekeihland.powerswitch.database.DatabaseHandler.openReadable(DatabaseHandler.java:18)
            at de.ekeihland.powerswitch.database.gateways.GatewayHandler.getAll(GatewayHandler.java:82)
            at de.ekeihland.powerswitch.network.NetworkHandler.searchGateways(NetworkHandler.java:89)
            at de.ekeihland.powerswitch.gui.activity.MainActivity$2.doInBackground(MainActivity.java:86)
            at de.ekeihland.powerswitch.gui.activity.MainActivity$2.doInBackground(MainActivity.java:81)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
06-11 19:44:45.991  32681-32705/de.ekeihland.powerswitch E/AutoDiscover﹕ Can't understand Gateway :( : unknown error (code 14): Could not open database
    HCGW:VC:Simple Solutions;MC:ConnAir433;FW:V014;IP:192.168.2.125;;
06-11 19:44:46.007  32681-32681/de.ekeihland.powerswitch E/SQLiteDatabase﹕ Failed to open database '/data/data/de.ekeihland.powerswitch/databases/PSdatabase.db'.
    android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
            at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
            at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:212)
            at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:196)
            at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:464)
            at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:186)
            at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:178)
            at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:916)
            at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:893)
            at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:796)
            at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1254)
            at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:267)
            at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
            at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
            at de.ekeihland.powerswitch.database.DatabaseHandler.openReadable(DatabaseHandler.java:18)
            at de.ekeihland.powerswitch.database.rooms.RoomHandler.getAllRooms(RoomHandler.java:62)
            at de.ekeihland.powerswitch.gui.fragment.RoomsFragment.fillListWithRooms(RoomsFragment.java:71)
            at de.ekeihland.powerswitch.gui.fragment.RoomsFragment.refreshReceivers(RoomsFragment.java:62)
            at de.ekeihland.powerswitch.gui.fragment.RoomsFragment.onCreateView(RoomsFragment.java:52)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
            at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:490)
            at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:1105)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:951)
            at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1473)
            at android.view.View.measure(View.java:17496)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5466)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
            at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:124)
            at android.view.View.measure(View.java:17496)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5466)
            at android.support.v7.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:444)
            at android.view.View.measure(View.java:17496)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5466)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
            at android.view.View.measure(View.java:17496)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5466)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1438)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:724)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:615)
            at android.view.View.measure(View.java:17496)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5466)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2636)
            at android.view.View.measure(View.java:17496)
            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2031)
            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1193)
            at android.view.ViewRootImpl.performTraversals(
06-11 19:44:46.008  32681-32681/de.ekeihland.powerswitch E/SQLiteOpenHelper﹕ Couldn't open PSdatabase.db for writing (will try read-only):
    android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
            at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
            at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:212)
            at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:196)
            at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:464)
            at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:186)
            at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:178)
            at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:916)
            at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:893)
            at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:796)
            at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1254)
            at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:267)
            at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
            at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
            at de.ekeihland.powerswitch.database.DatabaseHandler.openReadable(DatabaseHandler.java:18)
            at de.ekeihland.powerswitch.database.rooms.RoomHandler.getAllRooms(RoomHandler.java:62)
            at de.ekeihland.powerswitch.gui.fragment.RoomsFragment.fillListWithRooms(RoomsFragment.java:71)
            at de.ekeihland.powerswitch.gui.fragment.RoomsFragment.refreshReceivers(RoomsFragment.java:62)
            at de.ekeihland.powerswitch.gui.fragment.RoomsFragment.onCreateView(RoomsFragment.java:52)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
            at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:490)
            at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:1105)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:951)
            at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1473)
            at android.view.View.measure(View.java:17496)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5466)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
            at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:124)
            at android.view.View.measure(View.java:17496)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5466)
            at android.support.v7.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:444)
            at android.view.View.measure(View.java:17496)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5466)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
            at android.view.View.measure(View.java:17496)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5466)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1438)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:724)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:615)
            at android.view.View.measure(View.java:17496)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5466)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2636)
            at android.view.View.measure(View.java:17496)
            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2031)
            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1193)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1400)
06-11 19:44:46.008  32681-32681/de.ekeihland.powerswitch E/SQLiteLog﹕ (14) cannot open file at line 31279 of [9491ba7d73]
06-11 19:44:46.008  32681-32681/de.ekeihland.powerswitch E/SQLiteLog﹕ (14) os_unix.c:31279: (2) open(/data/data/de.ekeihland.powerswitch/databases/PSdatabase.db) -
06-11 19:44:46.009  32681-32681/de.ekeihland.powerswitch E/SQLiteDatabase﹕ Failed to open database '/data/data/de.ekeihland.powerswitch/databases/PSdatabase.db'.
    android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
            at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
            at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:212)
            at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:196)
            at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:464)
            at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:186)
            at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:178)
            at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:916)
            at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:893)
            at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:796)
            at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:234)
            at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
            at de.ekeihland.powerswitch.database.DatabaseHandler.openReadable(DatabaseHandler.java:18)
            at de.ekeihland.powerswitch.database.rooms.RoomHandler.getAllRooms(RoomHandler.java:62)
            at de.ekeihland.powerswitch.gui.fragment.RoomsFragment.fillListWithRooms(RoomsFragment.java:71)
            at de.ekeihland.powerswitch.gui.fragment.RoomsFragment.refreshReceivers(RoomsFragment.java:62)
            at de.ekeihland.powerswitch.gui.fragment.RoomsFragment.onCreateView(RoomsFragment.java:52)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
            at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:490)
            at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:1105)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:951)
            at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1473)
            at android.view.View.measure(View.java:17496)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5466)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
            at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:124)
            at android.view.View.measure(View.java:17496)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5466)
            at android.support.v7.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:444)
            at android.view.View.measure(View.java:17496)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5466)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
            at android.view.View.measure(View.java:17496)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5466)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1438)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:724)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:615)
            at android.view.View.measure(View.java:17496)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5466)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2636)
            at android.view.View.measure(View.java:17496)
            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2031)
            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1193)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1400)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1078)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImp
06-11 19:44:46.009  32681-32681/de.ekeihland.powerswitch D/AndroidRuntime﹕ Shutting down VM
06-11 19:44:46.016  32681-32681/de.ekeihland.powerswitch E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: de.ekeihland.powerswitch, PID: 32681
    android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
            at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
            at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:212)
            at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:196)
            at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:464)
            at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:186)
            at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:178)
            at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:916)
            at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:893)
            at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:796)
            at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:234)
            at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
            at de.ekeihland.powerswitch.database.DatabaseHandler.openReadable(DatabaseHandler.java:18)
            at de.ekeihland.powerswitch.database.rooms.RoomHandler.getAllRooms(RoomHandler.java:62)
            at de.ekeihland.powerswitch.gui.fragment.RoomsFragment.fillListWithRooms(RoomsFragment.java:71)
            at de.ekeihland.powerswitch.gui.fragment.RoomsFragment.refreshReceivers(RoomsFragment.java:62)
            at de.ekeihland.powerswitch.gui.fragment.RoomsFragment.onCreateView(RoomsFragment.java:52)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
            at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:490)
            at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:1105)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:951)
            at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1473)
            at android.view.View.measure(View.java:17496)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5466)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
            at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:124)
            at android.view.View.measure(View.java:17496)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5466)
            at android.support.v7.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:444)
            at android.view.View.measure(View.java:17496)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5466)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
            at android.view.View.measure(View.java:17496)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5466)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1438)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:724)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:615)
            at android.view.View.measure(View.java:17496)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5466)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2636)
            at android.view.View.measure(View.java:17496)
            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2031)
            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1193)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1400)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1078)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5875)
            at an
```

**Comment by markusressel** [comment]
Sehr alter Fehler, ist schon ewig nicht mehr aufgetreten. Vermutlich durch großflächige Änderungen an der Datenbank inzwischen behoben -> closed
